use crate::error::Span;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TokenKind {
    Eof,
    Int,
    Float,
    String,
    FString,
    Identifier,
    Fn,
    Val,
    Var,
    Ref,
    MutRef,
    Owned,
    Move,
    Struct,
    Data,
    Class,
    Enum,
    Match,
    When,
    If,
    Else,
    For,
    In,
    Loop,
    Return,
    Defer,
    While,
    Break,
    Continue,
    Extern,
    Pub,
    Import,
    True,
    False,
    And,
    Or,
    Not,
    Async,
    Await,
    Suspend,
    FatArrow,
    Arrow,
    QDot,
    Elvis,
    ColonColon,
    EqEq,
    Ne,
    Le,
    Ge,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Semi,
    Colon,
    Dot,
    Question,
    At,
    Eq,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Lt,
    Gt,
}

#[derive(Clone, Debug)]
pub struct Token {
    pub kind: TokenKind,
    pub text: String,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, text: impl Into<String>, span: Span) -> Self {
        Self {
            kind,
            text: text.into(),
            span,
        }
    }
}

pub fn keyword_kind(text: &str) -> TokenKind {
    match text {
        "fn" => TokenKind::Fn,
        "val" => TokenKind::Val,
        "var" => TokenKind::Var,
        "ref" => TokenKind::Ref,
        "mutref" => TokenKind::MutRef,
        "owned" => TokenKind::Owned,
        "move" => TokenKind::Move,
        "struct" => TokenKind::Struct,
        "data" => TokenKind::Data,
        "class" => TokenKind::Class,
        "enum" => TokenKind::Enum,
        "match" => TokenKind::Match,
        "when" => TokenKind::When,
        "if" => TokenKind::If,
        "else" => TokenKind::Else,
        "for" => TokenKind::For,
        "in" => TokenKind::In,
        "loop" => TokenKind::Loop,
        "return" => TokenKind::Return,
        "defer" => TokenKind::Defer,
        "while" => TokenKind::While,
        "break" => TokenKind::Break,
        "continue" => TokenKind::Continue,
        "extern" => TokenKind::Extern,
        "pub" => TokenKind::Pub,
        "import" => TokenKind::Import,
        "true" => TokenKind::True,
        "false" => TokenKind::False,
        "and" => TokenKind::And,
        "or" => TokenKind::Or,
        "not" => TokenKind::Not,
        "async" => TokenKind::Async,
        "await" => TokenKind::Await,
        "suspend" => TokenKind::Suspend,
        _ => TokenKind::Identifier,
    }
}

